# CMake generated Testfile for 
# Source directory: C:/Users/user/Desktop/Test_Scheduling_Proj/tests
# Build directory: C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ProgramCourseModelTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/Debug/program_course_model_test.exe")
  set_tests_properties(ProgramCourseModelTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;14;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ProgramCourseModelTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/Release/program_course_model_test.exe")
  set_tests_properties(ProgramCourseModelTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;14;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ProgramCourseModelTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/MinSizeRel/program_course_model_test.exe")
  set_tests_properties(ProgramCourseModelTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;14;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ProgramCourseModelTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/RelWithDebInfo/program_course_model_test.exe")
  set_tests_properties(ProgramCourseModelTest PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;14;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
else()
  add_test(ProgramCourseModelTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ParserPreprocessorIntegrationTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/Debug/parser_preprocessor_integration_test.exe")
  set_tests_properties(ParserPreprocessorIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests" _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;35;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ParserPreprocessorIntegrationTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/Release/parser_preprocessor_integration_test.exe")
  set_tests_properties(ParserPreprocessorIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests" _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;35;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ParserPreprocessorIntegrationTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/MinSizeRel/parser_preprocessor_integration_test.exe")
  set_tests_properties(ParserPreprocessorIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests" _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;35;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ParserPreprocessorIntegrationTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/RelWithDebInfo/parser_preprocessor_integration_test.exe")
  set_tests_properties(ParserPreprocessorIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests" _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;35;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
else()
  add_test(ParserPreprocessorIntegrationTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(SchedulerIntegrationTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/Debug/scheduler_integration_test.exe")
  set_tests_properties(SchedulerIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests" _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;63;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(SchedulerIntegrationTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/Release/scheduler_integration_test.exe")
  set_tests_properties(SchedulerIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests" _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;63;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(SchedulerIntegrationTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/MinSizeRel/scheduler_integration_test.exe")
  set_tests_properties(SchedulerIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests" _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;63;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(SchedulerIntegrationTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/RelWithDebInfo/scheduler_integration_test.exe")
  set_tests_properties(SchedulerIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests" _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;63;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
else()
  add_test(SchedulerIntegrationTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(InvalidInputIntegrationTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/Debug/invalid_input_integration_test.exe")
  set_tests_properties(InvalidInputIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests" _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;88;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(InvalidInputIntegrationTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/Release/invalid_input_integration_test.exe")
  set_tests_properties(InvalidInputIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests" _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;88;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(InvalidInputIntegrationTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/MinSizeRel/invalid_input_integration_test.exe")
  set_tests_properties(InvalidInputIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests" _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;88;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(InvalidInputIntegrationTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/RelWithDebInfo/invalid_input_integration_test.exe")
  set_tests_properties(InvalidInputIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests" _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;88;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
else()
  add_test(InvalidInputIntegrationTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(NoSolutionIntegrationTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/Debug/no_solution_integration_test.exe")
  set_tests_properties(NoSolutionIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests" _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;116;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(NoSolutionIntegrationTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/Release/no_solution_integration_test.exe")
  set_tests_properties(NoSolutionIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests" _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;116;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(NoSolutionIntegrationTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/MinSizeRel/no_solution_integration_test.exe")
  set_tests_properties(NoSolutionIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests" _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;116;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(NoSolutionIntegrationTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/RelWithDebInfo/no_solution_integration_test.exe")
  set_tests_properties(NoSolutionIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests" _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;116;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
else()
  add_test(NoSolutionIntegrationTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(OverlapConflictIntegrationTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/Debug/overlap_conflict_integration_test.exe")
  set_tests_properties(OverlapConflictIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests" _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;143;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(OverlapConflictIntegrationTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/Release/overlap_conflict_integration_test.exe")
  set_tests_properties(OverlapConflictIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests" _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;143;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(OverlapConflictIntegrationTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/MinSizeRel/overlap_conflict_integration_test.exe")
  set_tests_properties(OverlapConflictIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests" _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;143;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(OverlapConflictIntegrationTest "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests/tests/RelWithDebInfo/overlap_conflict_integration_test.exe")
  set_tests_properties(OverlapConflictIntegrationTest PROPERTIES  WORKING_DIRECTORY "C:/Users/user/Desktop/Test_Scheduling_Proj/build_integrated_tests" _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;143;add_test;C:/Users/user/Desktop/Test_Scheduling_Proj/tests/CMakeLists.txt;0;")
else()
  add_test(OverlapConflictIntegrationTest NOT_AVAILABLE)
endif()
