// This file is autogenerated. Changes will be overwritten.
#include <MXUWEOXILK/moc_AppController.cpp>
#include <MXUWEOXILK/moc_CalendarManager.cpp>
#include <MXUWEOXILK/moc_ProgramCourseModel.cpp>
#include <QSPQJSB54Z/moc_ScheduleGenerator.cpp>
#include <QSPQJSB54Z/moc_SchedulingWorker.cpp>
